import { ApiSection } from '@/components/ApiSection'
import { AuthSection } from '@/components/AuthSection'
import { DashboardSection } from '@/components/DashboardSection/DashboardSection'
import { StartProjectSection } from '@/components/StartProjectSection'
import { StoreSection } from '@/components/StoreSection'
import { Layout } from '@/components/layout/Layout'
import Head from 'next/head'
export default function Home() {


  return (
    <>
      <Head>
        <title>Supabase</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className='container relative px-6 mx-auto lg:px-16 xl:px-20'>
          <StoreSection />
          <DashboardSection />
          <ApiSection />
          <AuthSection />
          <StartProjectSection />
        </main>
      </Layout>
    </>
  )
}
